export const homeObjOne = {
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:false,
    topLine:'premium Bank',
    headLine:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart : false,
    img:require('../../images/svg-2.svg'),
    alt:'btc',
    dark:false,
    primary:true,
    darkText:false,
}
export const homeObjTwo = {
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'premium Bank',
    headLine:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Learn More',
    imgStart : true,
    img:require('../../images/svg-4.svg'),
    alt:'btc-tree',
    dark:false,
    primary:true,
    darkText:true,
}
export const homeObjThree = {
    id:'sign-up',
    lightBg:false,
    lightText:true,
    lightTextDesc:false,
    topLine:'premium Bank',
    headLine:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart : false,
    img:require('../../images/svg-8.svg'),
    alt:'Card',
    dark:false,
    primary:true,
    darkText:false,
}
